### ISSUE TITLE
bash is not available in the container

### ISSUE THREAD

**Issue by olvlvl** [motiv-labs/janus#126]
Our scripts expect `bash` to be available in containers, but only `sh` is available here. Is it a deliberate choice or could we add `bash`?

**Comment by ahelal** [comment]
Yes by design since. I am not sure what script you are talking about.
But generally I would recommend to use posix sh instead of bash and you can convert your script hashbang to ```#!/bin/sh```

We don't have any planes to support bash in containers. We moved to Alpine to keep footprint as low as possible
Hope that helps
