### ISSUE TITLE
How to avoid proxing traffic to disabled target

### ISSUE THREAD

**Issue by chendanshuang** [motiv-labs/janus#255]
If http://service1 is down, client will get 502. How to avoid traffic is proxied to service1?
```json
{
    "name" : "api",
    "active" : true,
    "proxy" : {
        "preserve_host" : false,
        "listen_path" : "/api/*",
        "upstreams" : {
            "balancing": "roundrobin",
            "targets": [
                {"target": "http://service1"},
                {"target": "http://service2"}
            ]
        },
        "strip_path" : false,
        "append_path" : true,
        "methods" : ["GET", "POST", "PUT", "DELETE"]
    }
}
```

**Comment by italolelis** [comment]
Hello @shuangstar,

Currently, we don't do checks on the `RountTrip` for how healthy your service is. If you have a single instance what should be the behavior? I think a single instance of service 1 that is 502ing should still 502, right?

If you have multiple instances then we can automatically check if your service is healthy and if it's not then we should remove from the targets `in memory` but not from your configuration.

At HelloFresh we have HAProxy for Client Side Load balancing that does all of this for us, that's why we never added to Janus yet.

It would be nice to get some help on this.

**Comment by rafaeljesus** [comment]
Hi @shuangstar we recently added the load balancing functionality https://github.com/hellofresh/janus/pull/212 since as @italolelis said we rely on Consul/HAProxy here. However given we are planning to add circuit breaker in the proxy layer, we can leverage on it's monitoring capabilities to remove the most failed services from the balancing algorithm. Stay tuned, most likely we are going to add it pretty soon!

**Comment by chendanshuang** [comment]
Thx!

"If you have multiple instances then we can automatically check if your service is healthy and if it's not then we should remove from the targets in memory but not from your configuration."

I did't watched this feature in my janus cluster. How to config it?

my api definition in my janus instances.
```
{
    "name" : "api",
    "active" : true,
    "proxy" : {
        "preserve_host" : false,
        "listen_path" : "/api/*",
        "upstreams" : {
            "balancing": "roundrobin",
            "targets": [
                {"target": "http://service1"},
                {"target": "http://service2"}
            ]
        },
        "strip_path" : false,
        "append_path" : true,
        "methods" : ["GET", "POST", "PUT", "DELETE"]
    }
}
```

**Comment by chendanshuang** [comment]
Great, I'm looking forward to the circuit breaker!

**Comment by rafaeljesus** [comment]
@shuangstar the circuit breaker was added recently, pls check this out https://github.com/hellofresh/janus/issues/301 I am gonna close this issue for now, fell free to reopen or open a new one, thanks

**Comment by chendanshuang** [comment]
```
If you have multiple instances then we can automatically check if your service is healthy and if it's not then we should remove from the targets in memory but not from your configuration.
```

@italolelis It looks not works for me.
